apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: my-app
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: nginx:latest
        
