apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  selector:
    app: my-app   # Ensure the pod has a matching label (app: my-app) in your pod definition
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8080
